call load.bat example/Patient1
call load.bat example/Patient2
call load.bat example/Patient3
call load.bat example/Patient4
call load.bat example/Patient5
call load.bat example/Patient6
call load.bat example/Patient7
call load.bat example/Patient8
call load.bat example/Patient9
call load.bat example/Patient10
call load.bat example/Patient11
call load.bat example/Patient12
call load.bat example/Patient13
call load.bat example/Patient14
call load.bat example/Patient15
